import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "MapThingF",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body className={inter.className}>
				<main>{children}</main>
				<nav>
					
				</nav>
			</body>
		</html>
	);
};

export default RootLayout;
